In [ ]:
"""Introduction to NumPy
1.NumPy is a Python library used for working with arrays.
2.NumPy is a library consisting of multidimensional array objects and a collection of routines for processing the arrays.
3.In Python we have lists that serve the purpose of arrays, but they are slow to process.
4.NumPy aims to provide an array object which works faster than traditional Python lists.
5.NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently."""

In [ ]:
'''
 Creation NumPy Arrays
➢ array()
0-Dimensional Arrays
1-Dimensional Arrays
2-Dimensional Arrays
3-Dimensional Arrays
➢ asarray() with nditer()
➢ frombuffer()
➢ fromiter()
'''

In [1]:
#O dimentional array
import numpy as np
a=np.array(10)
print(a)


10


In [3]:
# 1 Dimentional array
a= np.array([10,11,12,13,14])
print(a)


[10 11 12 13 14]


In [4]:
# 2 Dimentional array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Display the values in the array
print(a[0][1])

2


In [7]:
#3 Dimentional array
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
'''
np.asarray()
np.asarray() is used to convert an existing Python object such as a list, tuple, or another array into a NumPy array.
Syntax:
numpy.asarray(a, dtype=None)
'''

In [11]:
import numpy as np
a = [10, 20, 30, 40, 50]
arr = np.asarray(a, dtype=float)
print(arr)

[10. 20. 30. 40. 50.]


In [ ]:
'''
np.nditer()
np.nditer() is used to iterate efficiently through the elements of a NumPy array.
It is especially useful when working with multidimensional arrays.
Syntax
np.nditer(array)
'''

In [2]:
#Example 1: Iterating through a 1-D Array
import numpy as np
arr = np.array([[10, 20], [30, 40]])
print(arr)
#for x in np.nditer(arr,order='C'):
   # print(x)

[[10 20]
 [30 40]]


In [18]:
#Example 2: Iterating through a 2-D Array
import numpy as np
arr = np.array([[10, 20], [30, 40]])
print(arr)


[[10 20]
 [30 40]]


In [23]:
#Example 2: Iterating through a 2-D Array using Row major and column major order
import numpy as np
arr = np.array([[10, 20], [30, 40]])
b=np.nditer(arr, order='F')
for i in b:
    print(i)


10
30
20
40


In [ ]:
'''
np.frombuffer()
np.frombuffer() creates a NumPy array from data stored in a buffer-like object.
A buffer can be thought of as a block of memory containing raw binary data.
It is useful when working with:

Binary files
Byte data
Network data
Memory buffers
Raw binary data
Syntax:
np.frombuffer(buffer, dtype=float, count=-1, offset=0)
'''

In [3]:
import numpy as np
a = b"Hi welcome to my class"
arr = np.frombuffer(a, dtype="S1", count=6,offset=5)
print(arr)

[b'l' b'c' b'o' b'm' b'e' b' ']


In [ ]:
'''
np.fromiter()
np.fromiter() creates a NumPy array from an iterable object.
An iterable can be:
List
Tuple
Generator
range()
Set
Other objects that can be iterated
Syntax
np.fromiter(iterable, dtype)
The dtype parameter is required because NumPy needs to know what type of elements it should create.
'''

In [31]:
# read the values depends on range()
import numpy as np
arr = np.fromiter(range(5), dtype=int)
print(arr)

[0 1 2 3 4]


In [34]:
a=np.fromiter([10, 20, 30], dtype=int)       # List
print(a)
b=np.fromiter((10, 20, 30), dtype=float)       # Tuple
print(b)
c=np.fromiter(range(1, 4), dtype=int)        # range
print(c)
d=np.fromiter({10, 20, 30}, dtype=int)       # Set
print(d)
np.fromiter((x for x in range(3)), dtype=int) # Generator

[10 20 30]
[10. 20. 30.]
[1 2 3]
[10 20 30]


array([0, 1, 2])

In [ ]:
'''
Initialization of array using NumPy

1.Zeros()
it is used to initialize an empty array with zeros
By default data type is float
'''

In [35]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [38]:
#if you want to interger datatype
a=np.zeros(5,dtype=int)
print(a)
# for 2D array
a = np.zeros((2, 3), dtype=int)
print(a)

[0 0 0 0 0]
[[0 0 0]
 [0 0 0]]


In [39]:
#np.ones() — initialize with ones
a = np.ones(5, dtype=int)
print(a)

[1 1 1 1 1]


In [41]:
'''np.full() — initialize with a specific value. If you want every element to have the same value:'''
a = np.full(5, 7)
print(a)
a = np.full((2, 3), 5)
print(a)


[7 7 7 7 7]
[[5 5 5]
 [5 5 5]]


In [42]:
'''np.empty() — create an uninitialized array.The values are not initialized to zero. You may see arbitrary values.'''
a = np.empty(5)
print(a)

[3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]


In [47]:
'''np.arange() — initialize with a sequence. Similar to Python's range().'''

a = np.arange(1, 6)
print(a)

# can specify a step:

a = np.arange(0, 10, 2)
print(a)

[1 2 3 4 5]
[0 2 4 6 8]


In [48]:
'''np.linspace() — initialize with evenly spaced values. Create 5 evenly spaced values between 0 and 10, including both 0 and 10.'''
a = np.linspace(0, 10, 5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [50]:
#np.eye() — initialize an identity matrix
a = np.eye(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
'''Creating NumPy arrays
        │
        ├── From existing data
        │      └── np.array()
        │
        ├── Fill with a value
        │      ├── np.zeros()
        │      ├── np.ones()
        │      └── np.full()
        │
        ├── Generate sequences
        │      ├── np.arange()
        │      └── np.linspace()
        │
        ├── Special arrays
        │      ├── np.eye()
        │      └── np.empty()
        │
        └── From iterable
               └── np.fromiter()'''