In [1]:
#0 dimensional array 
import numpy as np 
a=np.array(10)
print(a)

10


In [2]:
#1 dimensional array
a=np.array([10,11,12,13,14])
print(a)

[10 11 12 13 14]


In [9]:
#2 dimensional array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#display the values in an array
print(a[0][1])

2


In [6]:
#3 dimensional array
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]


In [11]:
print(a[1][1],a[0][1])

5 2


In [14]:
#Range based arrays

c=np.arange(0,10,2)
print(c)

d=np.linspace(0,1,5)
print(d)

#pre-filled arrays
e=np.zeros((2,3))
print(e)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0.]
 [0. 0. 0.]]
